import '@styles/globals.css';
import { Inter } from 'next/font/google'
import { Sacramento } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const sacramento = Sacramento({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-sacramento',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={`${sacramento.variable}`} lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
